spring:
  profiles:
    active: dev
  application:
    name: breathchain-backend

server:
  port: 18080
  servlet:
    context-path: /api

# MyBatis-Plus 全局配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath*:mapper/**/*.xml

# 业务参数
breathchain:
  jwt:
    secret: ${BREATHCHAIN_JWT_SECRET:change-this-to-a-very-long-random-string-please-32bytes}
    expire-millis: 86400000  # 24h
    header: Authorization
    prefix: "Bearer "
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000
  blockchain:
    enabled: true
    node-url: http://127.0.0.1:18545
    chain-id: 20200
    gas-price: 1000000000
    gas-limit: 6721975
    # 由 setAwarder/setSubmitter 加入白名单的后端服务账户私钥（务必使用环境变量）
    service-private-key: ${BREATHCHAIN_SERVICE_KEY:0x8f3af6f123719a381dc5cd0649968f9b438b0a2b1ea47c2dcee9763c9e048a33}
    breath-token-address: ${BREATH_TOKEN_ADDR:0xEfBCA72429B4486C0172A4BF5426e2804028f025}
    training-record-address: ${TRAINING_RECORD_ADDR:0x54d59788Eb732d80cf66D756a1eAD3F7a64B6A6E}

logging:
  level:
    com.breathchain: debug
    org.web3j: info
